<template>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4 mt-5">
            <div class="loadingio-spinner-chunk-7whubcoornf">
                <div class="ldio-lqqsvss1b">
                    <div>
                        <div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4"></div>
    </div>
</template>

<script>
    export default {
        name: "Loader"
    }
</script>

<style scoped>
    @keyframes ldio-lqqsvss1b-r {
        0%, 25%, 50%, 75%, 100% { animation-timing-function: cubic-bezier(0,1,0,1) }
        0% { transform: scale(0.7000000000000001) rotate(180deg) }
        25% { transform: scale(0.7000000000000001) rotate(270deg) }
        50% { transform: scale(0.7000000000000001) rotate(360deg) }
        75% { transform: scale(0.7000000000000001) rotate(450deg) }
        100% { transform: scale(0.7000000000000001) rotate(540deg) }
    }
    @keyframes ldio-lqqsvss1b-z {
        0%, 50%, 100% { animation-timing-function: cubic-bezier(1,0,0,1) }
        0% { transform: scale(1) }
        50% { transform: scale(1) }
        100% { transform: scale(.5) }
    }
    @keyframes ldio-lqqsvss1b-p {
        0%, 50%, 100% { animation-timing-function: cubic-bezier(1,0,0,1) }
        0% { transform: scale(0) }
        50% { transform: scale(1) }
        100% { transform: scale(1) }
    }
    @keyframes ldio-lqqsvss1b-c {
        0%, 25%, 50%, 75%, 100% { animation-timing-function: cubic-bezier(0,1,0,1) }
        0% { background: #e15b64 }
        25% { background: #f47e60 }
        50% { background: #f8b26a }
        75% { background: #abbd81 }
        100% { background: #e15b64 }
    }
    .ldio-lqqsvss1b > div {
        animation: ldio-lqqsvss1b-r 3.571428571428571s linear infinite;
        transform-origin: 100px 100px;
    }
    .ldio-lqqsvss1b > div > div {
        width: 200px;
        height: 200px;
        position: absolute;
        animation: ldio-lqqsvss1b-z 0.8928571428571428s linear infinite;
        transform-origin: 200px 200px;
    }
    .ldio-lqqsvss1b > div > div div {
        position: absolute;
        width: 100px;
        height: 100px;
        background: #e15b64;
        transform-origin: 50px 50px
    }
    .ldio-lqqsvss1b > div > div div:nth-child(1) {
        left: 0px;
        top: 0px;
        animation: ldio-lqqsvss1b-p 0.8928571428571428s linear infinite, ldio-lqqsvss1b-c 3.571428571428571s linear infinite;
    }
    .ldio-lqqsvss1b > div > div div:nth-child(2) {
        left: 100px;
        top: 0px;
        animation: ldio-lqqsvss1b-p 0.8928571428571428s linear infinite, ldio-lqqsvss1b-c 3.571428571428571s linear infinite;
    }
    .ldio-lqqsvss1b > div > div div:nth-child(3) {
        left: 0px;
        top: 100px;
        animation: ldio-lqqsvss1b-p 0.8928571428571428s linear infinite, ldio-lqqsvss1b-c 3.571428571428571s linear infinite;
    }
    .ldio-lqqsvss1b > div > div div:nth-child(4) {
        left: 100px;
        top: 100px;
        transform: scale(1);
        animation: ldio-lqqsvss1b-c 3.571428571428571s linear infinite
    }
    .loadingio-spinner-chunk-7whubcoornf {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;
        background: #ffffff;
    }
    .ldio-lqqsvss1b {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }
    .ldio-lqqsvss1b div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>
